# fly.toml app configuration file for fraudshield

app = "fraudshield"
primary_region = "bom"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8501"

[http_service]
  internal_port = 8501
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
